version: '3.8'
services:
  articles-download:
    image: newsapi-pipeline
    container_name: articles-download-pipeline
    env_file:
      - .env.prod
    volumes:
      - ./newsapi-sa.json:/app/newsapi-sa.json

    command: " articles-download"

  sources-download:
    image: newsapi-pipeline
    container_name: sources-download-pipeline
    env_file:
      - .env.prod
    volumes:
      - ./newsapi-sa.json:/app/newsapi-sa.json

    command: " sources-download"

  articles-import:
    image: newsapi-pipeline
    container_name: articles-import-pipeline
    env_file:
      - .env.prod
    volumes:
      - ./newsapi-sa.json:/app/newsapi-sa.json

    command: " articles-import"

  sources-import:
    image: newsapi-pipeline
    container_name: sources-import-pipeline
    env_file:
      - .env.prod
    volumes:
      - ./newsapi-sa.json:/app/newsapi-sa.json

    command: " sources-import"
